   # CREDIT RISK MODEL USING TENSORFLOW

In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn.cross_validation import train_test_split

In [96]:
data = pd.read_csv('/Users/Shared/TensorFlow/tensorflow_tryouts/lending-club-data.csv', low_memory=False)

In [97]:
print data.columns

Index([u'id', u'member_id', u'loan_amnt', u'funded_amnt', u'funded_amnt_inv',
       u'term', u'int_rate', u'installment', u'grade', u'sub_grade',
       u'emp_title', u'emp_length', u'home_ownership', u'annual_inc',
       u'is_inc_v', u'issue_d', u'loan_status', u'pymnt_plan', u'url', u'desc',
       u'purpose', u'title', u'zip_code', u'addr_state', u'dti',
       u'delinq_2yrs', u'earliest_cr_line', u'inq_last_6mths',
       u'mths_since_last_delinq', u'mths_since_last_record', u'open_acc',
       u'pub_rec', u'revol_bal', u'revol_util', u'total_acc',
       u'initial_list_status', u'out_prncp', u'out_prncp_inv', u'total_pymnt',
       u'total_pymnt_inv', u'total_rec_prncp', u'total_rec_int',
       u'total_rec_late_fee', u'recoveries', u'collection_recovery_fee',
       u'last_pymnt_d', u'last_pymnt_amnt', u'next_pymnt_d',
       u'last_credit_pull_d', u'collections_12_mths_ex_med',
       u'mths_since_last_major_derog', u'policy_code', u'not_compliant',
       u'status', u'inactive_loans', u'bad_loans', u'emp_length_num',
       u'grade_num', u'sub_grade_num', u'delinq_2yrs_zero', u'pub_rec_zero',
       u'collections_12_mths_zero', u'short_emp', u'payment_inc_ratio',
       u'final_d', u'last_delinq_none', u'last_record_none',
       u'last_major_derog_none'],
      dtype='object')

In [80]:
features = ['grade',                     # grade of the loan
            'sub_grade',                 # sub-grade of the loan
            'short_emp',                 # one year or less of employment
            'emp_length_num',            # number of years of employment
            'home_ownership',            # home_ownership status: own, mortgage or rent
            'dti',                       # debt to income ratio
            'purpose',                   # the purpose of the loan
            'term',                      # the term of the loan
            'last_delinq_none',          # has borrower had a delinquincy
            'last_major_derog_none',     # has borrower had 90 day or worse rating
            'revol_util',                # percent of available credit being used
            'total_rec_late_fee',        # total late fees received to day
           ]

target = 'safe_loans'                   # prediction target (y) (+1 means safe, -1 is risky)

In [98]:
data[target] = data['bad_loans'].apply(lambda x : +1 if x==0 else 0)

In [63]:
print data.dtypes

id                               int64
member_id                        int64
loan_amnt                        int64
funded_amnt                      int64
funded_amnt_inv                  int64
term                            object
int_rate                       float64
installment                    float64
grade                           object
sub_grade                       object
emp_title                       object
emp_length                      object
home_ownership                  object
annual_inc                     float64
is_inc_v                        object
issue_d                         object
loan_status                     object
pymnt_plan                      object
url                             object
desc                            object
purpose                         object
title                           object
zip_code                        object
addr_state                      object
dti                            float64
delinq_2yrs                    float64
earliest_cr_line                object
inq_last_6mths                 float64
mths_since_last_delinq         float64
mths_since_last_record         float64
                                ...
total_pymnt_inv                float64
total_rec_prncp                float64
total_rec_int                  float64
total_rec_late_fee             float64
recoveries                     float64
collection_recovery_fee        float64
last_pymnt_d                    object
last_pymnt_amnt                float64
next_pymnt_d                    object
last_credit_pull_d              object
collections_12_mths_ex_med     float64
mths_since_last_major_derog    float64
policy_code                      int64
not_compliant                    int64
status                          object
inactive_loans                   int64
bad_loans                        int64
emp_length_num                   int64
grade_num                        int64
sub_grade_num                  float64
delinq_2yrs_zero               float64
pub_rec_zero                   float64
collections_12_mths_zero       float64
short_emp                        int64
payment_inc_ratio              float64
final_d                         object
last_delinq_none                 int64
last_record_none                 int64
last_major_derog_none            int64
safe_loans                       int64
dtype: object

In [64]:
data[features]

,grade,sub_grade,short_emp,emp_length_num,home_ownership,dti,purpose,term,last_delinq_none,last_major_derog_none,revol_util,total_rec_late_fee
0,B,B2,0,11,RENT,27.65,credit_card,36 months,1,1,83.70,0.00
1,C,C4,1,1,RENT,1.00,car,60 months,1,1,9.40,0.00
2,C,C5,0,11,RENT,8.72,small_business,36 months,1,1,98.50,0.00
3,C,C1,0,11,RENT,20.00,other,36 months,0,1,21.00,16.97
4,A,A4,0,4,RENT,11.20,wedding,36 months,1,1,28.30,0.00
5,E,E1,0,10,RENT,5.35,car,36 months,1,1,87.50,0.00
6,F,F2,0,5,OWN,5.55,small_business,60 months,1,1,32.60,0.00
7,B,B5,1,1,RENT,18.08,other,60 months,1,1,36.50,0.00
8,C,C3,0,6,OWN,16.12,debt_consolidation,60 months,1,1,20.60,0.00
9,B,B5,0,11,OWN,10.78,debt_consolidation,36 months,1,1,67.10,0.00
10,C,C1,1,1,RENT,10.08,debt_consolidation,36 months,1,1,91.70,0.00
11,B,B1,0,4,RENT,12.56,credit_card,36 months,1,1,43.10,0.00
12,B,B2,0,4,RENT,7.06,other,36 months,1,1,55.50,0.00
13,D,D1,1,1,RENT,20.31,debt_consolidation,36 months,1,1,81.50,0.00
14,C,C4,0,5,RENT,18.60,home_improvement,36 months,0,1,70.20,0.00
15,A,A1,0,11,MORTGAGE,10.52,major_purchase,36 months,1,1,16.00,0.00
16,B,B3,0,2,MORTGAGE,18.44,medical,36 months,0,1,37.73,15.00
17,A,A1,0,7,RENT,9.86,debt_consolidation,36 months,1,1,23.10,0.00
18,B,B4,0,11,RENT,13.22,debt_consolidation,36 months,1,1,90.30,0.00
19,B,B3,0,11,OWN,11.18,credit_card,36 months,1,1,82.40,0.00
20,B,B3,0,6,RENT,16.01,debt_consolidation,36 months,1,1,91.80,0.00
21,B,B3,0,2,RENT,2.40,major_purchase,36 months,1,1,29.70,0.00
22,B,B1,0,3,MORTGAGE,29.44,credit_card,36 months,1,1,93.90,0.00
23,C,C2,0,10,RENT,15.22,debt_consolidation,36 months,1,1,57.60,0.00
24,D,D2,0,3,RENT,13.97,other,60 months,0,1,59.50,0.00
25,B,B3,0,11,MORTGAGE,5.63,debt_consolidation,36 months,0,1,37.70,0.00
26,B,B3,1,1,RENT,12.19,credit_card,36 months,1,1,59.10,0.00
27,A,A3,0,8,MORTGAGE,20.34,debt_consolidation,36 months,1,1,86.90,0.00
28,A,A4,0,6,MORTGAGE,14.03,debt_consolidation,36 months,1,1,27.40,0.00
29,A,A5,0,3,RENT,11.93,debt_consolidation,36 months,0,1,29.30,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...
122577,A,A4,0,11,RENT,13.95,credit_card,36 months,1,1,48.00,0.00
122578,F,F2,0,7,MORTGAGE,13.85,small_business,60 months,1,1,61.20,0.00
122579,B,B2,0,9,MORTGAGE,9.63,debt_consolidation,36 months,0,1,59.20,0.00
122580,B,B5,0,2,RENT,27.75,debt_consolidation,36 months,1,1,83.60,0.00
122581,C,C5,1,1,RENT,15.60,debt_consolidation,36 months,1,1,46.70,0.00
122582,D,D3,0,11,MORTGAGE,15.73,credit_card,60 months,0,1,36.60,0.00
122583,C,C4,1,1,RENT,18.09,debt_consolidation,36 months,0,1,0.00,0.00
122584,C,C3,0,4,RENT,30.28,credit_card,36 months,0,1,43.60,0.00
122585,D,D5,0,7,OWN,23.58,debt_consolidation,60 months,0,1,51.60,0.00
122586,E,E2,0,4,MORTGAGE,22.83,medical,60 months,0,1,42.10,0.00
122587,C,C3,0,9,MORTGAGE,11.48,debt_consolidation,60 months,1,1,64.70,0.00
122588,A,A5,0,4,OWN,7.57,debt_consolidation,36 months,1,1,34.40,0.00
122589,C,C1,0,11,MORTGAGE,7.13,credit_card,60 months,0,1,69.80,0.00
122590,B,B5,1,1,OWN,19.62,small_business,36 months,1,1,68.50,0.00
122591,C,C3,0,4,MORTGAGE,14.02,credit_card,60 months,1,1,71.20,0.00
122592,B,B3,0,11,RENT,4.02,debt_consolidation,36 months,0,0,68.60,0.00
122593,E,E3,0,11,MORTGAGE,11.23,home_improvement,60 months,0,0,84.30,0.00
122594,C,C3,1,1,OWN,26.21,credit_card,36 months,1,1,28.40,0.00
122595,C,C2,0,11,MORTGAGE,7.21,credit_card,60 months,1,1,29.80,0.00
122596,D,D1,0,11,MORTGAGE,19.56,debt_consolidation,36 months,0,1,52.50,0.00
122597,E,E5,0,11,MORTGAGE,23.90,credit_card,60 months,0,1,57.00,0.00
122598,A,A5,0,3,MORTGAGE,14.60,medical,36 months,1,1,82.70,0.00
122599,G,G2,0,11,MORTGAGE,26.27,medical,60 months,0,0,94.10,0.00
122600,D,D3,1,1,RENT,6.41,other,36 months,0,1,55.90,0.00
122601,B,B5,0,5,MORTGAGE,18.69,debt_consolidation,36 months,0,1,29.50,0.00
122602,E,E5,1,0,MORTGAGE,1.50,medical,60 months,0,0,14.60,0.00
122603,D,D2,0,11,MORTGAGE,11.26,debt_consolidation,36 months,0,0,15.20,0.00
122604,D,D3,0,6,MORTGAGE,12.28,medical,60 months,0,0,10.70,0.00
122605,D,D5,0,11,MORTGAGE,18.45,debt_consolidation,60 months,1,1,46.30,0.00
122606,A,A4,0,4,OWN,5.39,credit_card,36 months,0,1,21.50,0.00

In [142]:
CATEGORICAL_COLUMNS = ["grade", "sub_grade", "home_ownership",
                       "purpose", "term"]
CONTINUOUS_COLUMNS = ["emp_length_num", "dti", "revol_util", "total_rec_late_fee", "short_emp", "last_delinq_none", "last_major_derog_none"]

LABEL_COLUMN = [target]

In [143]:
training_set, test_set = train_test_split(data, test_size = 0.2)

In [144]:
print len(training_set)
print len(test_set)

98085
24522

In [145]:
def input_fn(df):
    # Creates a dictionary mapping from each continuous feature column name (k) to
    # the values of that column stored in a constant Tensor.
    continuous_cols = {k: tf.constant(df[k].values)
                       for k in CONTINUOUS_COLUMNS}
    # Creates a dictionary mapping from each categorical feature column name (k)
    # to the values of that column stored in a tf.SparseTensor.
    categorical_cols = {k: tf.SparseTensor(
        indices=[[i, 0] for i in range(df[k].size)],
        values=df[k].values,
        shape=[df[k].size, 1])
                        for k in CATEGORICAL_COLUMNS}
    # Merges the two dictionaries into one.
    feature_cols = dict(continuous_cols.items() + categorical_cols.items())
    # Converts the label column into a constant Tensor.
    label = tf.constant(df[LABEL_COLUMN].values)
    # Returns the feature columns and the label.
    return feature_cols, label

def train_input_fn():
    return input_fn(training_set)

def eval_input_fn():
    return input_fn(test_set)

In [146]:
grade_keys = list(data['grade'].unique())
sub_grade_keys = list(data['sub_grade'].unique())
home_ownership_keys = list(data['home_ownership'].unique())
purpose_keys = list(data['purpose'].unique())
term_keys = list(data['term'].unique())

In [147]:
print "grade_keys: ",grade_keys
print "sub_grade_keys: ",sub_grade_keys
print "home_ownership_keys: ",home_ownership_keys
print "purpose_keys: ",purpose_keys
print "term_keys: ",term_keys

grade_keys:  ['B', 'C', 'A', 'E', 'F', 'D', 'G']
sub_grade_keys:  ['B2', 'C4', 'C5', 'C1', 'A4', 'E1', 'F2', 'B5', 'C3', 'B1', 'D1', 'A1', 'B3', 'B4', 'C2', 'D2', 'A3', 'A5', 'D5', 'A2', 'E4', 'D3', 'D4', 'F3', 'E3', 'F1', 'E5', 'G4', 'E2', 'G2', 'F5', 'F4', 'G5', 'G1', 'G3']
home_ownership_keys:  ['RENT', 'OWN', 'MORTGAGE', 'OTHER']
purpose_keys:  ['credit_card', 'car', 'small_business', 'other', 'wedding', 'debt_consolidation', 'home_improvement', 'major_purchase', 'medical', 'moving', 'vacation', 'house']
term_keys:  [' 36 months', ' 60 months']

In [148]:
grade = tf.contrib.layers.sparse_column_with_keys(
  column_name="grade", keys=grade_keys)
sub_grade = tf.contrib.layers.sparse_column_with_keys(
  column_name="sub_grade", keys=sub_grade_keys)
home_ownership = tf.contrib.layers.sparse_column_with_keys(
  column_name="home_ownership", keys=home_ownership_keys)
purpose = tf.contrib.layers.sparse_column_with_keys(
  column_name="purpose", keys=purpose_keys)
term = tf.contrib.layers.sparse_column_with_keys(
  column_name="term", keys=term_keys)

In [149]:
emp_length_num = tf.contrib.layers.real_valued_column("emp_length_num")
dti = tf.contrib.layers.real_valued_column("dti")
revol_util = tf.contrib.layers.real_valued_column("revol_util")
total_rec_late_fee = tf.contrib.layers.real_valued_column("total_rec_late_fee")
short_emp = tf.contrib.layers.real_valued_column("short_emp")
last_delinq_none = tf.contrib.layers.real_valued_column("last_delinq_none")
last_major_derog_none = tf.contrib.layers.real_valued_column("last_major_derog_none")

In [150]:
import tempfile

In [151]:
model_dir = tempfile.mkdtemp()
model = tf.contrib.learn.LinearClassifier(feature_columns=[grade, sub_grade, short_emp, emp_length_num, 
                                                           home_ownership, dti, purpose, term, last_delinq_none, 
                                                           last_major_derog_none, revol_util, total_rec_late_fee],
  model_dir=model_dir)

In [152]:
model.fit(input_fn=train_input_fn, steps=200)

WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.

LinearClassifier()

In [153]:
results = model.evaluate(input_fn=eval_input_fn, steps=1)
for key in sorted(results):
    print "%s: %s" % (key, results[key])

WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.

accuracy: 0.678737
eval_auc: 0.0
loss: 0.187504

In [154]:
model_reg_dir = tempfile.mkdtemp()
model_reg = tf.contrib.learn.LinearClassifier(feature_columns=[grade, sub_grade, short_emp, emp_length_num, 
                                                           home_ownership, dti, purpose, term, last_delinq_none, 
                                                           last_major_derog_none, revol_util, total_rec_late_fee],
                                          optimizer=tf.train.FtrlOptimizer(
                                                        learning_rate=0.1,
                                                        l1_regularization_strength=5,
                                                        l2_regularization_strength=5),
                                        model_dir=model_dir)

In [155]:
model_reg.fit(input_fn=train_input_fn, steps=200)

WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.

LinearClassifier()

In [156]:
results = model_reg.evaluate(input_fn=eval_input_fn, steps=1)
for key in sorted(results):
    print "%s: %s" % (key, results[key])

WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.

accuracy: 0.678737
eval_auc: 0.0
loss: 0.187504

In [157]:
model.linear_weights_

{'linear/dti_weight': array([[-0.03771699]], dtype=float32),
 'linear/emp_length_num_weight': array([[ 0.01967828]], dtype=float32),
 'linear/grade_weights': array([[ 0.43817055],
        [ 0.14012535],
        [ 1.01390278],
        [-0.35323787],
        [-0.65565318],
        [-0.1863524 ],
        [-0.22389808]], dtype=float32),
 'linear/home_ownership_weights': array([[-0.05679193],
        [ 0.06166209],
        [ 0.32435447],
        [-0.01863182]], dtype=float32),
 'linear/last_delinq_none_weight': array([[-0.08802346]], dtype=float32),
 'linear/last_major_derog_none_weight': array([[ 0.03810053]], dtype=float32),
 'linear/purpose_weights': array([[  3.84579808e-01],
        [  1.63014546e-01],
        [ -7.22101271e-01],
        [ -1.19044095e-01],
        [  1.18902937e-01],
        [  1.60974890e-01],
        [  5.58535941e-02],
        [  1.67711556e-01],
        [ -3.96581180e-02],
        [ -4.02224064e-03],
        [ -6.32864598e-04],
        [  2.22200863e-02]], dtype=float32),
 'linear/revol_util_weight': array([[-0.0033562]], dtype=float32),
 'linear/short_emp_weight': array([[-0.04605752]], dtype=float32),
 'linear/sub_grade_weights': array([[ 0.2647602 ],
        [-0.01470482],
        [-0.01212853],
        [ 0.17268451],
        [ 0.31239969],
        [-0.01286686],
        [-0.08229071],
        [-0.05404489],
        [ 0.00124967],
        [ 0.28982487],
        [ 0.08226527],
        [ 0.31375745],
        [ 0.18138392],
        [ 0.03616794],
        [ 0.16285524],
        [-0.07559682],
        [ 0.26081368],
        [ 0.14723362],
        [-0.06287193],
        [ 0.29469112],
        [-0.14620546],
        [-0.02600728],
        [-0.0627192 ],
        [-0.15099849],
        [-0.03104708],
        [-0.12009708],
        [-0.11747317],
        [ 0.00445024],
        [-0.06373498],
        [-0.04980864],
        [-0.14939833],
        [-0.17742455],
        [-0.0339148 ],
        [-0.09853718],
        [-0.04676006]], dtype=float32),
 'linear/term_weights': array([[ 0.39632609],
        [-0.42234984]], dtype=float32),
 'linear/total_rec_late_fee_weight': array([[-4.36058617]], dtype=float32)}

# ADDING MORE FEATURES

In [109]:
data[features]

,grade,sub_grade_num,short_emp,emp_length_num,home_ownership,dti,purpose,payment_inc_ratio,delinq_2yrs,delinq_2yrs_zero,...,pub_rec_zero,revol_util,total_rec_late_fee,int_rate,total_rec_int,annual_inc,funded_amnt,funded_amnt_inv,installment,safe_loans
0,B,0.4,0,11,RENT,27.65,credit_card,8.143500,0.0,1.0,...,1.0,83.70,0.00,10.65,861.07,24000.0,5000,4975,162.87,1
1,C,0.8,1,1,RENT,1.00,car,2.393200,0.0,1.0,...,1.0,9.40,0.00,15.27,435.17,30000.0,2500,2500,59.83,-1
2,C,1.0,0,11,RENT,8.72,small_business,8.259550,0.0,1.0,...,1.0,98.50,0.00,15.96,603.65,12252.0,2400,2400,84.33,1
3,C,0.2,0,11,RENT,20.00,other,8.275850,0.0,1.0,...,1.0,21.00,16.97,13.49,2209.33,49200.0,10000,10000,339.31,1
4,A,0.8,0,4,RENT,11.20,wedding,5.215330,0.0,1.0,...,1.0,28.30,0.00,7.90,631.38,36000.0,5000,5000,156.46,1
5,E,0.2,0,10,RENT,5.35,car,2.735750,0.0,1.0,...,1.0,87.50,0.00,18.64,938.14,48000.0,3000,3000,109.43,1
6,F,0.4,0,5,OWN,5.55,small_business,4.571700,0.0,1.0,...,1.0,32.60,0.00,21.28,294.94,40000.0,5600,5600,152.39,-1
7,B,1.0,1,1,RENT,18.08,other,9.716000,0.0,1.0,...,1.0,36.50,0.00,12.69,533.42,15000.0,5375,5350,121.45,-1
8,C,0.6,0,6,OWN,16.12,debt_consolidation,2.557500,0.0,1.0,...,1.0,20.60,0.00,14.65,1177.52,72000.0,6500,6500,153.45,1
9,B,1.0,0,11,OWN,10.78,debt_consolidation,6.440640,0.0,1.0,...,1.0,67.10,0.00,12.69,1943.08,75000.0,12000,12000,402.54,1
10,C,0.2,1,1,RENT,10.08,debt_consolidation,12.215200,0.0,1.0,...,1.0,91.70,0.00,13.49,570.26,30000.0,9000,9000,305.38,-1
11,B,0.2,0,4,RENT,12.56,credit_card,7.734400,0.0,1.0,...,1.0,43.10,0.00,9.91,478.98,15000.0,3000,3000,96.68,1
12,B,0.4,0,4,RENT,7.06,other,3.908880,0.0,1.0,...,1.0,55.50,0.00,10.65,1393.42,100000.0,10000,10000,325.74,-1
13,D,0.2,1,1,RENT,20.31,debt_consolidation,1.513290,0.0,1.0,...,1.0,81.50,0.00,16.29,270.17,28000.0,1000,1000,35.31,1
14,C,0.8,0,5,RENT,18.60,home_improvement,9.942290,0.0,1.0,...,1.0,70.20,0.00,15.27,2519.26,42000.0,10000,10000,347.98,1
15,A,0.2,0,11,MORTGAGE,10.52,major_purchase,1.195310,0.0,1.0,...,1.0,16.00,0.00,6.03,185.02,110000.0,3600,3600,109.57,1
16,B,0.6,0,2,MORTGAGE,18.44,medical,2.835140,2.0,0.0,...,1.0,37.73,15.00,11.71,1149.50,84000.0,6000,6000,198.46,1
17,A,0.2,0,7,RENT,9.86,debt_consolidation,4.342080,0.0,1.0,...,1.0,23.10,0.00,6.03,259.96,77385.0,9200,9200,280.01,1
18,B,0.8,0,11,RENT,13.22,debt_consolidation,8.019770,0.0,1.0,...,1.0,90.30,0.00,12.42,3330.44,105000.0,21000,21000,701.73,-1
19,B,0.6,0,11,OWN,11.18,credit_card,7.938240,0.0,1.0,...,1.0,82.40,0.00,11.71,1902.56,50000.0,10000,10000,330.76,1
20,B,0.6,0,6,RENT,16.01,debt_consolidation,7.938240,0.0,1.0,...,1.0,91.80,0.00,11.71,1536.31,50000.0,10000,10000,330.76,1
21,B,0.6,0,2,RENT,2.40,major_purchase,3.133580,0.0,1.0,...,1.0,29.70,0.00,11.71,475.25,76000.0,6000,6000,198.46,-1
22,B,0.2,0,3,MORTGAGE,29.44,credit_card,6.304960,0.0,1.0,...,1.0,93.90,0.00,9.91,823.48,92000.0,15000,15000,483.38,1
23,C,0.4,0,10,RENT,15.22,debt_consolidation,10.292800,0.0,1.0,...,1.0,57.60,0.00,14.27,0.00,60000.0,15000,8725,514.64,-1
24,D,0.4,0,3,RENT,13.97,other,2.967360,3.0,0.0,...,1.0,59.50,0.00,16.77,719.11,50004.0,5000,5000,123.65,-1
25,B,0.6,0,11,MORTGAGE,5.63,debt_consolidation,1.497850,1.0,0.0,...,1.0,37.70,0.00,11.71,484.79,106000.0,4000,4000,132.31,1
26,B,0.6,1,1,RENT,12.19,credit_card,13.495200,0.0,1.0,...,1.0,59.10,0.00,11.71,1622.21,25000.0,8500,8500,281.15,1
27,A,0.6,0,8,MORTGAGE,20.34,debt_consolidation,9.547110,0.0,1.0,...,1.0,86.90,0.00,7.51,523.54,17108.0,4375,4375,136.11,1
28,A,0.8,0,6,MORTGAGE,14.03,debt_consolidation,15.933100,0.0,1.0,...,1.0,27.40,0.00,7.90,3061.08,75000.0,31825,31825,995.82,1
29,A,1.0,0,3,RENT,11.93,debt_consolidation,7.923970,0.0,1.0,...,1.0,29.30,0.00,8.90,714.59,24044.0,5000,5000,158.77,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122577,A,0.8,0,11,RENT,13.95,credit_card,9.133620,0.0,1.0,...,1.0,48.00,0.00,7.90,333.45,37000.0,9000,9000,281.62,1
122578,F,0.4,0,7,MORTGAGE,13.85,small_business,7.409490,0.0,1.0,...,1.0,61.20,0.00,24.08,1625.79,70000.0,15000,15000,432.22,1
122579,B,0.4,0,9,MORTGAGE,9.63,debt_consolidation,13.158000,1.0,0.0,...,1.0,59.20,0.00,10.99,741.17,62692.0,21000,20800,687.42,1
122580,B,1.0,0,2,RENT,27.75,debt_consolidation,6.632090,0.0,1.0,...,1.0,83.60,0.00,13.53,445.95,43000.0,7000,6900,237.65,-1
122581,C,1.0,1,1,RENT,15.60,debt_consolidation,10.582900,0.0,1.0,...,1.0,46.70,0.00,16.24,1190.93,33000.0,8250,8250,291.03,1
122582,D,0.6,0,11,MORTGAGE,15.73,credit_card,8.654240,0.0,1.0,...,1.0,36.60,0.00,18.25,1518.27,35400.0,10000,10000,255.30,1
122583,C,0.8,1,1,RENT,18.09,debt_consolidation,14.685300,0.0,1.0,...,1.0,0.00,0.00,15.61,460.65,27000.0,9450,9450,330.42,-1
122584,C,0.6,0,4,RENT,30.28,credit_card,17.154800,4.0,0.0,...,1.0,43.60,0.00,14.98,1426.18,30000.0,12375,12375,428.87,1
122585,D,1.0,0,7,OWN,23.58,debt_consolidation,11.681800,0.0,1.0,...,1.0,51.60,0.00,19.97,1808.11,75000.0,27575,27575,730.11,1
122586,E,0.4,0,4,MORTGAGE,22.83,medical,10.692200,1.0,0.0,...,1.0,42.10,0.00,21.48,2189.70,55200.0,18000,18000,491.84,1
122587,C,0.6,0,9,MORTGAGE,11.48,debt_consolidation,6.341240,0.0,1.0,...,1.0,64.70,0.00,14.98,1374.08,126000.0,28000,28000,665.83,-1
122588,A,1.0,0,4,OWN,7.57,debt_consolidation,3.556400,0.0,1.0,...,1.0,34.40,0.00,8.90,103.84,150000.0,14000,14000,444.55,1
122589,C,0.2,0,11,MORTGAGE,7.13,credit_card,7.442530,0.0,1.0,...,1.0,69.80,0.00,13.98,2890.19,90000.0,24000,23800,558.19,1
122590,B,1.0,1,1,OWN,19.62,small_business,11.010800,0.0,1.0,...,1.0,68.50,0.00,13.53,828.78,37000.0,10000,10000,339.50,-1
122591,C,0.6,0,4,MORTGAGE,14.02,credit_card,6.658300,0.0,1.0,...,1.0,71.20,0.00,14.98,2999.44,120000.0,28000,28000,665.83,1
122592,B,0.6,0,11,RENT,4.02,debt_consolidation,4.981500,1.0,0.0,...,0.0,68.60,0.00,11.99,733.05,80000.0,10000,9925,332.10,1
122593,E,0.6,0,11,MORTGAGE,11.23,home_improvement,8.115430,0.0,1.0,...,1.0,84.30,0.00,22.40,3034.68,70000.0,17000,17000,473.40,1
122594,C,0.6,1,1,OWN,26.21,credit_card,8.154410,0.0,1.0,...,0.0,28.40,0.00,14.98,292.88,40800.0,8000,8000,277.25,-1
122595,C,0.4,0,11,MORTGAGE,7.21,credit_card,3.385860,0.0,1.0,...,1.0,29.80,0.00,14.47,2739.93,200000.0,24000,24000,564.31,1
122596,D,0.2,0,11,MORTGAGE,19.56,debt_consolidation,17.824000,1.0,0.0,...,0.0,52.50,0.00,16.99,2369.60,84000.0,35000,35000,1247.68,-1
122597,E,1.0,0,11,MORTGAGE,23.90,credit_card,11.702700,1.0,0.0,...,1.0,57.00,0.00,23.40,1358.58,102000.0,35000,35000,994.73,1
122598,A,1.0,0,3,MORTGAGE,14.60,medical,1.465570,0.0,1.0,...,1.0,82.70,0.00,8.90,208.77,130000.0,5000,5000,158.77,1
122599,G,0.4,0,11,MORTGAGE,26.27,medical,14.323200,1.0,0.0,...,1.0,94.10,0.00,25.83,2537.29,60000.0,24000,23925,716.16,1
122600,D,0.6,1,1,RENT,6.41,other,2.720870,0.0,1.0,...,1.0,55.90,0.00,18.25,822.38,96000.0,6000,6000,217.67,1
122601,B,1.0,0,5,MORTGAGE,18.69,debt_consolidation,5.432000,1.0,0.0,...,1.0,29.50,0.00,13.53,497.25,45000.0,6000,6000,203.70,-1
122602,E,1.0,1,0,MORTGAGE,1.50,medical,4.487630,1.0,0.0,...,1.0,14.60,0.00,23.40,347.78,45600.0,6000,6000,170.53,-1
122603,D,0.4,0,11,MORTGAGE,11.26,debt_consolidation,10.117800,1.0,0.0,...,0.0,15.20,0.00,17.57,654.95,65000.0,15250,15250,548.05,1
122604,D,0.6,0,6,MORTGAGE,12.28,medical,6.958120,4.0,0.0,...,1.0,10.70,0.00,18.25,510.45,37536.0,8525,8525,217.65,-1
122605,D,1.0,0,11,MORTGAGE,18.45,debt_consolidation,8.961540,0.0,1.0,...,0.0,46.30,0.00,19.97,2840.88,78000.0,22000,22000,582.50,-1
122606,A,0.8,0,4,OWN,5.39,credit_card,0.904916,3.0,0.0,...,1.0,21.50,0.00,7.90,126.58,83000.0,2000,2000,62.59,1

In [113]:
features = ['grade',                     # grade of the loan (categorical)
            'sub_grade_num',             # sub-grade of the loan as a number from 0 to 1
            'short_emp',                 # one year or less of employment
            'emp_length_num',            # number of years of employment
            'home_ownership',            # home_ownership status: own, mortgage or rent
            'dti',                       # debt to income ratio
            'purpose',                   # the purpose of the loan
            'payment_inc_ratio',         # ratio of the monthly payment to income
            'delinq_2yrs',               # number of delinquincies 
            'delinq_2yrs_zero',          # no delinquincies in last 2 years
            'inq_last_6mths',            # number of creditor inquiries in last 6 months
            'last_delinq_none',          # has borrower had a delinquincy
            'last_major_derog_none',     # has borrower had 90 day or worse rating
            'open_acc',                  # number of open credit accounts
            'pub_rec',                   # number of derogatory public records
            'pub_rec_zero',              # no derogatory public records
            'revol_util',                # percent of available credit being used
            'total_rec_late_fee',        # total late fees received to day
            'int_rate',                  # interest rate of the loan
            'total_rec_int',             # interest received to date
            'annual_inc',                # annual income of borrower
            'funded_amnt',               # amount committed to the loan
            'funded_amnt_inv',           # amount committed by investors for the loan
            'installment',               # monthly payment owed by the borrower
           ]

In [111]:
data_clean  = data[features].dropna()

In [112]:
len(data_clean)

122578

In [92]:
data_clean = data_temp.dropna()

In [93]:
len(data_clean)

122607

In [115]:
training_set, test_set = train_test_split(data_clean, test_size = 0.2)
print len(training_set)
print len(test_set)

98062
24516

In [116]:
tensor_features = {}
CATEGORICAL_COLUMNS = []
CONTINUOUS_COLUMNS = []

for i in features:
    if (data[i].dtype == 'int64') or (data[i].dtype == 'float64'):
        CONTINUOUS_COLUMNS.append(i) 
        tensor_features[i] = tf.contrib.layers.real_valued_column(i)
    else:
        CATEGORICAL_COLUMNS.append(i)
        tensor_features[i] = tf.contrib.layers.sparse_column_with_keys(
                              column_name=i, keys=list(data[i].unique()))

In [117]:
print tensor_features['grade']

_SparseColumn(column_name='grade', is_integerized=False, bucket_size=None, lookup_config=_SparseIdLookupConfig(vocabulary_file=None, keys=('B', 'C', 'A', 'E', 'F', 'D', 'G'), num_oov_buckets=0, vocab_size=7, default_value=-1), weight_column=None, combiner='sum', dtype=tf.string)

In [118]:
print tensor_features['annual_inc']

_RealValuedColumn(column_name='annual_inc', dimension=1, default_value=None, dtype=tf.float32)

In [119]:
CATEGORICAL_COLUMNS

['grade', 'home_ownership', 'purpose']

In [120]:
CONTINUOUS_COLUMNS

['sub_grade_num',
 'short_emp',
 'emp_length_num',
 'dti',
 'payment_inc_ratio',
 'delinq_2yrs',
 'delinq_2yrs_zero',
 'inq_last_6mths',
 'last_delinq_none',
 'last_major_derog_none',
 'open_acc',
 'pub_rec',
 'pub_rec_zero',
 'revol_util',
 'total_rec_late_fee',
 'int_rate',
 'total_rec_int',
 'annual_inc',
 'funded_amnt',
 'funded_amnt_inv',
 'installment']

In [134]:
model_dir = tempfile.mkdtemp()
model = tf.contrib.learn.LinearClassifier(feature_columns=[tensor_features['grade'],                     # grade of the loan (categorical)
            tensor_features['sub_grade_num'],             # sub-grade of the loan as a number from 0 to 1
            tensor_features['short_emp'],                 # one year or less of employment
            tensor_features['emp_length_num'],            # number of years of employment
            tensor_features['home_ownership'],            # home_ownership status: own, mortgage or rent
            tensor_features['dti'],                       # debt to income ratio
            tensor_features['purpose'],                   # the purpose of the loan
           tensor_features['payment_inc_ratio'],         # ratio of the monthly payment to income
#            tensor_features['delinq_2yrs'],               # number of delinquincies 
#            tensor_features['delinq_2yrs_zero'],          # no delinquincies in last 2 years
#            tensor_features['inq_last_6mths'],            # number of creditor inquiries in last 6 months
            tensor_features['last_delinq_none'],          # has borrower had a delinquincy
#            tensor_features['last_major_derog_none'],     # has borrower had 90 day or worse rating
#            tensor_features['open_acc'],                  # number of open credit accounts
#            tensor_features['pub_rec'],                   # number of derogatory public records
#            tensor_features['pub_rec_zero'],              # no derogatory public records
            tensor_features['revol_util'],                # percent of available credit being used
            tensor_features['total_rec_late_fee'],        # total late fees received to day
#            tensor_features['int_rate'],                  # interest rate of the loan
#            tensor_features['total_rec_int'],             # interest received to date
            tensor_features['annual_inc']],                # annual income of borrower
#           tensor_features['funded_amnt'],               # amount committed to the loan
#            tensor_features['funded_amnt_inv'],           # amount committed by investors for the loan
#            tensor_features['installment']],               # monthly payment owed by the borrower
  model_dir=model_dir)

In [ ]:
'grade',                     # grade of the loan
            'sub_grade',                 # sub-grade of the loan
            'short_emp',                 # one year or less of employment
            'emp_length_num',            # number of years of employment
            'home_ownership',            # home_ownership status: own, mortgage or rent
            'dti',                       # debt to income ratio
            'purpose',                   # the purpose of the loan
            'term',                      # the term of the loan
            'last_delinq_none',          # has borrower had a delinquincy
            'last_major_derog_none',     # has borrower had 90 day or worse rating
            'revol_util',                # percent of available credit being used
            'total_rec_late_fee',        # total late fees received to day
           ]

In [139]:
model.fit(input_fn=train_input_fn, steps=200)

WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.

LinearClassifier()

In [140]:
results = model.evaluate(input_fn=eval_input_fn, steps=1)
for key in sorted(results):
    print "%s: %s" % (key, results[key])

WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.
WARNING:tensorflow:create_partitioned_variables is deprecated.  Use tf.get_variable with a partitioner set, or tf.get_partitioned_variable_list, instead.

accuracy: 0.0
eval_auc: 0.0
loss: 444.698

In [141]:
model.weights_

{'linear/annual_inc_weight': array([[-0.00838672]], dtype=float32),
 'linear/dti_weight': array([[-1.29763913]], dtype=float32),
 'linear/emp_length_num_weight': array([[-0.62183005]], dtype=float32),
 'linear/grade_weights': array([[ 0.68759507],
        [-1.14004457],
        [ 2.54913735],
        [-2.71312141],
        [-2.34279203],
        [-2.51851296],
        [-0.69874597]], dtype=float32),
 'linear/home_ownership_weights': array([[-1.32648158],
        [-0.48917532],
        [-0.09501822],
        [-0.02884799]], dtype=float32),
 'linear/last_delinq_none_weight': array([[-0.69723344]], dtype=float32),
 'linear/purpose_weights': array([[ 0.28210583],
        [ 0.27676743],
        [-1.41750586],
        [-1.05768549],
        [ 0.07574984],
        [-0.9525066 ],
        [ 0.14560367],
        [ 0.31382683],
        [-0.2215791 ],
        [-0.15563148],
        [-0.0113038 ],
        [-0.03260896]], dtype=float32),
 'linear/revol_util_weight': array([[-1.31407404]], dtype=float32),
 'linear/short_emp_weight': array([[-0.9698934]], dtype=float32),
 'linear/sub_grade_num_weight': array([[-0.79440641]], dtype=float32),
 'linear/total_rec_late_fee_weight': array([[-6.71851397]], dtype=float32)}